apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\KomposeTool\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: k8sconfig
  name: k8sconfig
spec:
  ports:
  - name: "80"
    port: 5046
    targetPort: 80
  selector:
    io.kompose.service: k8sconfig
  type: LoadBalancer
status:
  loadBalancer: {}
